version: "2.4"
services: 
  # MySQL
  #db:
  #  image: mysql:8.0.17
  #  ports:
  #  - 0.0.0.0:3306:3306
  #  environment:
  #  - MYSQL_ROOT_PASSWORD=lumis
  #  - MYSQL_DATABASE=trunk
  #  - MYSQL_USER=lumis
  #  - MYSQL_PASSWORD=lumis
  #  command: --max-connections=1000 --max-allowed-packet=256M --log-bin-trust-function-creators=1 --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #  security_opt:
  #  - seccomp:unconfined
  #  volumes: 
  #  - /c/lumis/trunk/env/mysql/data:/var/lib/mysql
  
  # SQL Server
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment: 
    - ACCEPT_EULA=Y
    - SA_PASSWORD=${SQL_SERVER_SA_PASSWD}
    ports: 
    - 0.0.0.0:1433:1433
    
    ## Volumes aren't working in this image
    # volumes: 
    # - /c/lumis/trunk/env/sqlserver/data:/var/opt/mssql

  # # Oracle
  # db:
  #   image: repo.lumis.com.br:12345/lumis/oracle-database-18c-xe:latest
  #   ports:
  #   - 0.0.0.0:1521:1521
  #   - 0.0.0.0:5500:5500
  #   - 0.0.0.0:5580:8080

  bd:
    build: elasticsearch/config/build
    ports: 
    - 0.0.0.0:9200:9200
    - 0.0.0.0:9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
    - bootstrap.memory_lock=true
    - ES_JAVA_OPTS=${ES_JAVA_OPTS:--Xms800m -Xmx800m}
    - discovery.type=single-node
    mem_limit: ${ES_MEM_LIMIT:-1500M}
    volumes: 
    - ${ES_LUMIS_ANALYSIS_SHARE:?Opss.....Lumis analysis share is required}:/usr/share/elasticsearch/config/lumis-analysis:ro
    # - /c/lumis/trunk/svnroot/Lumis_PortalJava/portal_install/lumisdata/shared/data/elasticsearch/lumis-analysis:/usr/share/elasticsearch/config/lumis-analysis:ro
    #- /c/lumis/trunk/env/elasticsearch/data/node-data:/usr/share/elasticsearch/data
    
  k:
    image: docker.elastic.co/kibana/kibana:7.2.1
    ports:
    - 0.0.0.0:5601:5601
    environment:
    - ELASTICSEARCH_HOSTS=http://bd:9200

  ws:
    image: nginx:1.17.3
    ports: 
    - 0.0.0.0:80:80
    - 0.0.0.0:443:443
    volumes: 
    - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/config/keys:/lumis/keys:ro
    - ${WWW_DIR:?Opppsss....WWW Dir is required}:/lumis/html:ro

  selenium-test:
    build: selenium-test/config/build
    # volumes:
    # - /dev/urandom:/dev/random
    # - /dev/shm:/dev/shm
    ports:
    - 0.0.0.0:4444:4444
    - 0.0.0.0:5900:5900
    mem_limit: 500M

  selenium-doc:
    image: selenium/standalone-chrome-debug:3.141.59
    volumes:
    - /dev/shm:/dev/shm
    # - /dev/urandom:/dev/random
    ports:
    - 0.0.0.0:4444:4444
    - 0.0.0.0:5900:5900
    mem_limit: 800M

  # appserver1:
  #   build: tomcat/config/build
  #   ports:
  #   - 0.0.0.0:8081:8080
  #   - 0.0.0.0:8001:8000
  #   mem_limit: 1G
  #   volumes: 
  #   - /c/lumis/trunk/svnroot/Lumis_PortalJava/portal_install/www:/usr/local/tomcat/webapps/ROOT
  #   - /c/lumis/trunk/svnroot/Lumis_PortalJava/portal_install/lumisdata:/lumis/lumisdata
  #   - /c/lumis/trunk/svnroot/Lumis_PortalJava/portal_install/lib/shared:/usr/local/tomcat/shared
  
  # appserver2:
  #   build: tomcat/config/build
  #   ports:
  #   - 0.0.0.0:8082:8080
  #   - 0.0.0.0:8002:8000
  #   mem_limit: 1G
  #   volumes: 
  #   - /c/lumis/trunk/svnroot/Lumis_PortalJava/portal_install/www:/usr/local/tomcat/webapps/ROOT
  #   - /c/lumis/trunk/svnroot/Lumis_PortalJava/portal_install/lumisdata2:/lumis/lumisdata
  #   - /c/lumis/trunk/svnroot/Lumis_PortalJava/portal_install/lib/shared:/usr/local/tomcat/shared

  em:
    image: rnwood/smtp4dev:linux-amd64-3.1.0-ci0868
    ports: 
    - 0.0.0.0:10800:80
    - 0.0.0.0:2525:25
