version: "2.4"
services: 
  # MySQL
  #db:
  #  image: mysql:8.0.17
  #  ports:
  #  - 127.0.0.1:3306:3306
  #  environment:
  #  - MYSQL_ROOT_PASSWORD=lumis
  #  - MYSQL_DATABASE=trunk
  #  - MYSQL_USER=lumis
  #  - MYSQL_PASSWORD=lumis
  #  command: --max-connections=1000 --max-allowed-packet=256M --log-bin-trust-function-creators=1 --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #  security_opt:
  #  - seccomp:unconfined
  #  volumes: 
  #  - /c/lumis/trunk/env/mysql/data:/var/lib/mysql
  
  # SQL Server
  db:
    image: mcr.microsoft.com/mssql/server:2022-CU10-ubuntu-22.04
    environment: 
    - ACCEPT_EULA=Y
    - SA_PASSWORD=Lum!1s!!
    ports: 
    - 127.0.0.1:1433:1433
    volumes: 
    - sqlserver-data:/var/opt/mssql

  # # Oracle
  # db:
  #   image: repo.lumis.com.br:12345/lumis/oracle-database-18c-xe:latest
  #   ports:
  #   - 127.0.0.1:1521:1521
  #   - 127.0.0.1:5500:5500
  #   - 127.0.0.1:5580:8080

  bd:
    build: elasticsearch/config/build
    ports: 
    - 127.0.0.1:9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
    - bootstrap.memory_lock=true
    - ES_JAVA_OPTS=-Xms800m -Xmx800m
    - discovery.type=single-node
    - xpack.security.enabled=false
    mem_limit: 1500M
    volumes: 
    - ../svnroot/Lumis_PortalJava/portal_install/lumisdata/shared/data/elasticsearch/lumis-analysis:/usr/share/elasticsearch/config/lumis-analysis:ro
    - elasticsearch-data:/usr/share/elasticsearch/data
    
  k:
    image: docker.elastic.co/kibana/kibana:8.11.3
    ports:
    - 127.0.0.1:5601:5601
    environment:
    - ELASTICSEARCH_HOSTS=http://bd:9200
    - SERVER_PUBLICBASEURL=http://kibana
    - xpack.security.enabled=false
    depends_on:
    - bd

  ws:
    image: httpd:2.4.58
    ports: 
    - 0.0.0.0:80:80
    - 0.0.0.0:443:443
    volumes:
    - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    - ../svnroot/Lumis_PortalJava/portal_install/www:/lumis/website/default:ro

  selenium-test:
    image: selenium/standalone-firefox-debug:3.141.59-20210422
    volumes:
    - /dev/urandom:/dev/random
    - /dev/shm:/dev/shm
    ports:
    - 127.0.0.1:4444:4444
    - 127.0.0.1:5900:5900
    mem_limit: 700M
    extra_hosts: 
    - "pclumis153:192.168.1.170"

  selenium-doc:
    image: selenium/standalone-chrome-debug:3.141.59
    volumes:
    - /dev/shm:/dev/shm
    # - /dev/urandom:/dev/random
    ports:
    - 127.0.0.1:4444:4444
    - 127.0.0.1:5900:5900
    mem_limit: 800M
    extra_hosts: 
    - "pclumis153:192.168.1.170"

  # appserver1:
  #   build: tomcat/config/build
  #   ports:
  #   - 127.0.0.1:8081:8080
  #   - 127.0.0.1:8001:8000
  #   mem_limit: 1G
  #   volumes: 
  #   - /mnt/c/lumis/trunk/svnroot/Lumis_PortalJava/portal_install/www:/usr/local/tomcat/webapps/ROOT
  #   - /mnt/c/lumis/trunk/svnroot/Lumis_PortalJava/portal_install/lumisdata:/lumis/lumisdata
  #   - /mnt/c/lumis/trunk/svnroot/Lumis_PortalJava/portal_install/lib/shared:/usr/local/tomcat/shared
  
  # appserver2:
  #   build: tomcat/config/build
  #   ports:
  #   - 127.0.0.1:8082:8080
  #   - 127.0.0.1:8002:8000
  #   mem_limit: 1G
  #   volumes: 
  #   - /mnt/c/lumis/trunk/svnroot/Lumis_PortalJava/portal_install/www:/usr/local/tomcat/webapps/ROOT
  #   - /mnt/c/lumis/trunk/svnroot/Lumis_PortalJava/portal_install/lumisdata2:/lumis/lumisdata
  #   - /mnt/c/lumis/trunk/svnroot/Lumis_PortalJava/portal_install/lib/shared:/usr/local/tomcat/shared

  em:
    image: rnwood/smtp4dev:3.1.2-ci20201230100
    ports: 
    - 127.0.0.1:10800:80
    - 127.0.0.1:25:25

volumes:
  sqlserver-data:
  elasticsearch-data: